use std::collections::HashMap;
use std::fs;

const CENTROID_DIMENSIONS: usize = 512;

fn extract_embedding_sparse(text: &str) -> [f32; CENTROID_DIMENSIONS] {
    let mut embedding = [0.0f32; CENTROID_DIMENSIONS];
    let text = text.to_lowercase();
    for window in text.as_bytes().windows(4) {
        let mut h: u64 = 0x811c9dc5;
        for &b in window {
            h ^= b as u64;
            h = h.wrapping_mul(0x01000193);
        }
        let idx = (h % CENTROID_DIMENSIONS as u64) as usize;
        embedding[idx] += 1.0;
    }
    let norm: f32 = embedding.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm > 0.0 {
        for val in embedding.iter_mut() {
            *val /= norm;
        }
    }
    embedding
}

fn main() {
    let corpus_json = fs::read_to_string("verification/semantic_corpus.json").unwrap();
    let v: serde_json::Value = serde_json::from_str(&corpus_json).unwrap();
    let categories = v["categories"].as_object().unwrap();

    let mut cluster_centroids = HashMap::new();

    for (cat_name, samples) in categories {
        let samples = samples.as_array().unwrap();
        let mut sum_vec = [0.0f32; CENTROID_DIMENSIONS];
        for sample in samples {
            let s = sample.as_str().unwrap();
            let emb = extract_embedding_sparse(s);
            for i in 0..CENTROID_DIMENSIONS {
                sum_vec[i] += emb[i];
            }
        }
        // Average
        for i in 0..CENTROID_DIMENSIONS {
            sum_vec[i] /= samples.len() as f32;
        }
        // Re-normalize centroid
        let norm: f32 = sum_vec.iter().map(|x| x * x).sum::<f32>().sqrt();
        if norm > 0.0 {
            for val in sum_vec.iter_mut() {
                *val /= norm;
            }
        }
        cluster_centroids.insert(cat_name.clone(), sum_vec);
    }

    // Generate Rust Code
    println!("// AUTOGENERATED by bootstrap_centroids.rs");
    println!("// Source: verification/semantic_corpus.json");
    println!("\npub const CENTROID_DIMENSIONS: usize = {};", CENTROID_DIMENSIONS);
    println!("pub const NUM_CENTROIDS: usize = {};", cluster_centroids.len());
    println!("\n#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]\npub enum CentroidId {{");
    for name in cluster_centroids.keys() {
        println!("    {},", name);
    }
    println!("}}\n");

    println!("pub const ATTACK_CENTROIDS: &[(CentroidId, [f32; {}])] = &[", CENTROID_DIMENSIONS);
    for (name, vec) in &cluster_centroids {
        print!("    (CentroidId::{}, [", name);
        for (i, val) in vec.iter().enumerate() {
            print!("{:.6}", val);
            if i < CENTROID_DIMENSIONS - 1 { print!(", "); }
        }
        println!("]),");
    }
    println!("];");
    println!("\npub const EXPECTED_CENTROID_HASH: &str = \"BOOTSTRAPPED\";");
}
