apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "policy-gate.fullname" . }}-config
  labels:
    {{- include "policy-gate.labels" . | nindent 4 }}
data:
  firewall.toml: |
    {{ .Values.firewallConfig | nindent 4 }}
