{{- if or .Values.proxy.initToken .Values.proxy.hmacKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policy-gate.fullname" . }}-secret
  labels:
    {{- include "policy-gate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.proxy.initToken }}
  init-token: {{ .Values.proxy.initToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.proxy.hmacKey }}
  hmac-key: {{ .Values.proxy.hmacKey | b64enc | quote }}
  {{- end }}
{{- end }}
