#!/usr/bin/env python3
"""
generate_centroids.py — Generate semantic centroids for Channel D

This script implements the IEC 61508 systematic capability process:
1. Load reference datasets from verification/semantic_corpus.json
2. Extract embeddings using frozen FastText/MiniLM
3. Run K-Means clustering to identify attack centroids (k=16)
4. Generate Rust code with frozen constants
5. Compute EXPECTED_CENTROID_HASH for CI tripwire
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import List, Tuple, Dict

import numpy as np
from sklearn.cluster import KMeans


def load_corpus(path: Path) -> Tuple[List[str], List[str]]:
    """Load semantic corpus from JSON file. Returns (texts, source_categories)."""
    if not path.exists():
        print(f"Error: Corpus file {path} not found.")
        sys.exit(1)
    
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    texts = []
    sources = []
    for category, samples in data.get("categories", {}).items():
        for sample in samples:
            texts.append(sample)
            sources.append(category)
            
    return texts, sources


def extract_fasttext_embeddings(texts: List[str]) -> np.ndarray:
    """Extract embeddings using FastText (300-dim)."""
    try:
        import fasttext
        import fasttext.util
    except ImportError:
        print("Error: fasttext not installed. Run: pip install fasttext")
        sys.exit(1)
    
    model_path = Path("cc.en.300.bin")
    if not model_path.exists():
        print("Downloading FastText English model...")
        fasttext.util.download_model('en', if_exists='ignore')
    
    model = fasttext.load_model(str(model_path))
    
    embeddings = []
    for text in texts:
        words = text.lower().split()
        if words:
            vectors = [model.get_word_vector(w) for w in words]
            embedding = np.mean(vectors, axis=0)
        else:
            embedding = np.zeros(300)
        embeddings.append(embedding)
    
    return np.array(embeddings)


def extract_minilm_embeddings(texts: List[str]) -> np.ndarray:
    """Extract embeddings using sentence-transformers/all-MiniLM-L6-v2 (384-dim)."""
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError:
        print("Error: sentence-transformers not installed. Run: pip install sentence-transformers")
        sys.exit(1)
    
    model = SentenceTransformer('all-MiniLM-L6-v2')
    embeddings = model.encode(texts, show_progress_bar=True)
    return embeddings


def cluster_embeddings(embeddings: np.ndarray, n_clusters: int = 16) -> Tuple[np.ndarray, np.ndarray]:
    """Run K-Means clustering on embeddings."""
    print(f"Running K-Means with k={n_clusters} on {len(embeddings)} samples...")
    
    kmeans = KMeans(
        n_clusters=n_clusters,
        random_state=42,
        n_init=10,
        max_iter=300
    )
    labels = kmeans.fit_predict(embeddings)
    centroids = kmeans.cluster_centers_
    
    for i in range(n_clusters):
        count = np.sum(labels == i)
        print(f"  Cluster {i}: {count} samples")
    
    return centroids, labels


def assign_cluster_names(centroids: np.ndarray, texts: List[str], sources: List[str], labels: np.ndarray) -> Dict[int, str]:
    """Assign human-readable names to clusters based on majority source category."""
    names = {}
    for i in range(len(centroids)):
        cluster_indices = [j for j, label in enumerate(labels) if label == i]
        cluster_sources = [sources[j] for j in cluster_indices]
        
        if not cluster_sources:
            names[i] = f"Unknown{i}"
            continue
            
        # Majority vote for category name
        from collections import Counter
        majority_cat = Counter(cluster_sources).most_common(1)[0][0]
        
        # Add index to ensure uniqueness if multiple clusters map to same category
        count_so_far = sum(1 for n in names.values() if n.startswith(majority_cat))
        name = f"{majority_cat}{count_so_far + 1}"
        names[i] = name
        
        print(f"\nCluster {i} -> {name}:")
        for j in cluster_indices[:2]:
            print(f"  - {texts[j]}")
            
    return names


def compute_centroid_hash(centroids: np.ndarray, names: Dict[int, str]) -> str:
    """Compute SHA-256 hash of centroids for CI tripwire."""
    h = hashlib.sha256()
    for i in sorted(names.keys()):
        h.update(names[i].encode())
        h.update(centroids[i].tobytes())
    return h.hexdigest()


def generate_rust_code(centroids: np.ndarray, names: Dict[int, str], dims: int) -> str:
    """Generate Rust code with frozen centroid constants."""
    centroid_hash = compute_centroid_hash(centroids, names)
    
    code = f'''// AUTOGENERATED by generate_centroids.py
// DO NOT EDIT MANUALLY — Run: python scripts/generate_centroids.py
//
// Safety Action SA-050: Semantic analysis using learned embeddings.
// Generated from verification/semantic_corpus.json via K-Means (k={len(centroids)}).
//
// Timestamp: {__import__('datetime').datetime.now().isoformat()}

pub const EXPECTED_CENTROID_HASH: &str = "{centroid_hash}";
pub const CENTROID_DIMENSIONS: usize = {dims};
pub const NUM_CENTROIDS: usize = {len(centroids)};

pub const ATTACK_CENTROIDS: &[(CentroidId, [f32; {dims}])] = &[
'''
    
    for i in range(len(centroids)):
        name = names[i]
        values = ", ".join(f"{v:.6f}" for v in centroids[i])
        code += f'    (CentroidId::{name}, [{values}]),\n'
    
    code += '];\n\n#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]\npub enum CentroidId {\n'
    for i in range(len(centroids)):
        code += f'    {names[i]},\n'
    code += '}\n'
    
    return code


def main():
    parser = argparse.ArgumentParser(description="Generate semantic centroids for Channel D")
    parser.add_argument("--corpus", type=Path, default=Path("verification/semantic_corpus.json"),
                       help="Path to semantic corpus JSON")
    parser.add_argument("--model", choices=["fasttext", "minilm"], default="minilm",
                       help="Embedding model to use")
    parser.add_argument("--dims", type=int, default=None,
                       help="Embedding dimensions (300 for fasttext, 384 for minilm)")
    parser.add_argument("--clusters", type=int, default=16,
                       help="Number of K-Means clusters")
    parser.add_argument("--output", type=Path, default=None,
                       help="Output Rust file path")
    args = parser.parse_args()
    
    print(f"Loading corpus from {args.corpus}...")
    texts, sources = load_corpus(args.corpus)
    print(f"  Loaded {len(texts)} samples across {len(set(sources))} categories.")
    
    if args.model == "fasttext":
        dims = args.dims or 300
        embeddings = extract_fasttext_embeddings(texts)
    else:
        dims = args.dims or 384
        embeddings = extract_minilm_embeddings(texts)
    
    centroids, labels = cluster_embeddings(embeddings, n_clusters=args.clusters)
    names = assign_cluster_names(centroids, texts, sources, labels)
    
    if args.output:
        print(f"\nGenerating Rust code to {args.output}...")
        code = generate_rust_code(centroids, names, dims)
        args.output.write_text(code)
        print(f"  Written {len(code)} bytes")
        print(f"  EXPECTED_CENTROID_HASH: {compute_centroid_hash(centroids, names)}")
    else:
        print(f"\nCentroids generated: {len(centroids)} clusters, {dims} dimensions")
        print(f"EXPECTED_CENTROID_HASH: {compute_centroid_hash(centroids, names)}")


if __name__ == "__main__":
    main()
